# Generated by Django 2.1.7 on 2020-02-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
