# Generated by Django 2.1.7 on 2020-02-01 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200201_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='summary',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
